name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate documentation
      run: |
        # Create Doxygen config
        cat > Doxyfile << 'EOF'
        PROJECT_NAME = "NetMgr"
        PROJECT_VERSION = "1.0.0"
        INPUT = src/
        RECURSIVE = YES
        GENERATE_HTML = YES
        GENERATE_LATEX = NO
        OUTPUT_DIRECTORY = docs/
        HTML_OUTPUT = html
        EXTRACT_ALL = YES
        EXTRACT_PRIVATE = YES
        EXTRACT_STATIC = YES
        GENERATE_TREEVIEW = YES
        HAVE_DOT = YES
        CALL_GRAPH = YES
        CALLER_GRAPH = YES
        EOF
        
        doxygen Doxyfile

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'docs/html'

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v3
